server {
	listen 3434;
	root srv/www;
	autoindex on;
	error_page 404 srv/www/customErrorPages/404.html;

	location / {
		allow_methods GET;
	}

	location /readOnly/ {
		allow_methods GET;
	}

	location /upload/ {
		allow_methods GET POST DELETE;
	}

	location /redirect/ {
		return 301 http://github.com;
	}
}

server {
	listen 8080;
	root srv/www;
	autoindex off;
	error_page 404 srv/www/customErrorPages/404bis.html;

	location / {
		allow_methods GET;
	}

	location /readOnly/ {
		allow_methods GET;
	}

	location /test/ {
		allow_methods GET POST;
		upload_path /uploadBis;
	}

	location /redirect/ {
		return 301 https://profile.intra.42.fr/;
	}
}