server {
		listen 3434;
		listen 8080;
		root srv/www;
		autoindex on;
		error_page 404 srv/www/customErrorPages/404.html;

		location /readOnly/ {
			allow_methods GET;
			return 301 http://github.com;
		}
}