server {
		listen 127.0.0.1:3434;
		root srv/www;
		autoindex on;
		error_page 404 srv/www/customErrorPages/404.html;
		index index.html;
		max_body_size 1M;
		server_name mysite.com;

		location / {
			cgi_extension .py /usr/bin/python3;
			cgi_extension .php /usr/bin/php-cgi;
			cgi_extension .sh /usr/bin/bash;
		}
		location /readOnly/ {
			allow_methods GET;
		}

		location /test/ {
			index dontexist.html;
		}

		location /redirect/ {
			return 301 http://github.com;
		}
}

