server {
	listen 127.0.0.1:3434;
	server_name example.com;
	root srv/www/example;
	index index.html;
}

server {
	listen 127.0.0.1:3434;
	server_name site.com;
	root srv/www/site;
	index index.html;
}
